# 数据库链接信息
DB_NAME: maxkb
DB_HOST: localhost
DB_PORT: 5432
DB_USER: postgres
DB_PASSWORD: root
DB_ENGINE: django.db.backends.postgresql

# 模型路径配置
MODEL_PATH: J:/MaxKB/data/model
MODEL_CACHE_FOLDER: J:/MaxKB/data/model/cache

# 向量模型配置
EMBEDDING_MODEL_NAME: shibing624/text2vec-base-chinese
EMBEDDING_MODEL_PATH: J:/MaxKB/data/model
EMBEDDING_DEVICE: cpu 

# 时区设置
TIME_ZONE: Asia/Shanghai
USE_TZ: true
LANGUAGE_CODE: zh-hans 