# Generated by Django 4.2.18 on 2025-06-05 08:51

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('function_lib', '0002_functionlib_is_active_functionlib_permission_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='functionlib',
            name='function_type',
            field=models.CharField(choices=[('PYTHON', 'Python'), ('SQL', 'SQL')], default='PYTHON', max_length=20, verbose_name='函数类型'),
        ),
        migrations.AddField(
            model_name='functionlib',
            name='icon',
            field=models.CharField(default='icon_function_outlined.svg', max_length=128, verbose_name='图标'),
        ),
        migrations.AddField(
            model_name='functionlib',
            name='init_field_list',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.JSONField(default=dict, verbose_name='初始化字段'), default=list, size=None, verbose_name='初始化字段列表'),
        ),
    ]
