# Generated by Django 4.2.18 on 2025-06-05 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('function_lib', '0003_functionlib_function_type_functionlib_icon_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='functionlib',
            name='init_field_list',
            field=models.JSONField(default=dict, verbose_name='初始化字段列表'),
        ),
    ]
