# Generated by Django 4.2.18 on 2025-06-06 02:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_user_language'),
        ('application', '0025_alter_application_prologue'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='asker',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='users.user', verbose_name='提问者'),
        ),
    ]
