# Generated by Django 4.2.18 on 2025-06-06 02:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0002_alter_chat_asker'),
        ('application', '0026_chat_asker'),
    ]

    operations = [
    ]
